<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pmbelayouts"
 *
 * Auto generated by Extension Builder 2018-01-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'BE-Layouts',
    'description' => 'Various Backend Layouts',
    'category' => 'distribution',
    'author' => 'Markus Puffer',
    'author_email' => 'm.puffer@pm-webdesign.eu',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
